In [2]:
#Shreyas Bansode
#Fds Assignment 3 Set B
#Roll no:6
#Batch 1


import pandas as pd
import numpy as np

In [6]:
#Question 1
df= pd.read_csv('winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [14]:
#Question 2
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(scaler.fit(df))

MinMaxScaler()


In [16]:
print(scaler.transform(df))

[[0.24778761 0.39726027 0.         ... 0.13772455 0.15384615 0.4       ]
 [0.28318584 0.52054795 0.         ... 0.20958084 0.21538462 0.4       ]
 [0.28318584 0.43835616 0.04       ... 0.19161677 0.21538462 0.4       ]
 ...
 [0.15044248 0.26712329 0.13       ... 0.25149701 0.4        0.6       ]
 [0.11504425 0.35958904 0.12       ... 0.22754491 0.27692308 0.4       ]
 [0.12389381 0.13013699 0.47       ... 0.19760479 0.4        0.6       ]]


In [17]:
#Question 3
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
print(ss.fit(df))

StandardScaler()


In [18]:
print(ss.transform(df))

[[-0.52835961  0.96187667 -1.39147228 ... -0.57920652 -0.96024611
  -0.78782264]
 [-0.29854743  1.96744245 -1.39147228 ...  0.1289504  -0.58477711
  -0.78782264]
 [-0.29854743  1.29706527 -1.18607043 ... -0.04808883 -0.58477711
  -0.78782264]
 ...
 [-1.1603431  -0.09955388 -0.72391627 ...  0.54204194  0.54162988
   0.45084835]
 [-1.39015528  0.65462046 -0.77526673 ...  0.30598963 -0.20930812
  -0.78782264]
 [-1.33270223 -1.21684919  1.02199944 ...  0.01092425  0.54162988
   0.45084835]]


In [25]:
#Question 4
from sklearn.preprocessing import Normalizer
print(Normalizer(1).fit(df))

Normalizer(norm=1)


In [26]:
print(Normalizer().transform(df))

[[0.19347777 0.01830195 0.         ... 0.01464156 0.24576906 0.13072822]
 [0.10698874 0.01207052 0.         ... 0.00932722 0.13442175 0.06858252]
 [0.13494887 0.01314886 0.00069205 ... 0.01124574 0.16955114 0.08650569]
 ...
 [0.1222319  0.00989496 0.00252225 ... 0.01455142 0.21342078 0.11641133]
 [0.10524769 0.01150589 0.00214063 ... 0.0126654  0.18195363 0.08919296]
 [0.12491328 0.00645385 0.00978487 ... 0.01374046 0.22900768 0.12491328]]


In [30]:
#Question 5
from sklearn.preprocessing import Binarizer
print(Binarizer().fit(X))

Binarizer()


In [31]:
print(Binarizer().transform(df))

[[1. 1. 0. ... 1. 1. 1.]
 [1. 1. 0. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
